// Copyright 2018 The Flutter team. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Ma liste de courses',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Ma liste de courses'),
        ),
        body: Center(
          child: ListView(
            children: [
              Text("Du pain", style: TextStyle(fontSize: 30)),
              Text("Du chocolat", style: TextStyle(fontSize: 30)),
              Text("Du curry", style: TextStyle(fontSize: 30)),
              Text("De la Pauline", style: TextStyle(fontSize: 30)),
              Text("Des Malterser", style: TextStyle(fontSize: 30)),
              Text("Du pain", style: TextStyle(fontSize: 30)),
              Text("Du chocolat", style: TextStyle(fontSize: 30)),
              Text("Du curry", style: TextStyle(fontSize: 30)),
              Text("De la Pauline", style: TextStyle(fontSize: 30)),
              Text("Des Malterser", style: TextStyle(fontSize: 30)),
              Text("Du pain", style: TextStyle(fontSize: 30)),
              Text("Du chocolat", style: TextStyle(fontSize: 30)),
              Text("Du curry", style: TextStyle(fontSize: 30)),
              Text("De la Pauline", style: TextStyle(fontSize: 30)),
              Text("Des Malterser", style: TextStyle(fontSize: 30)),
              Text("Du pain", style: TextStyle(fontSize: 30)),
              Text("Du chocolat", style: TextStyle(fontSize: 30)),
              Text("Du curry", style: TextStyle(fontSize: 30)),
              Text("De la Pauline", style: TextStyle(fontSize: 30)),
              Text("Des Malterser", style: TextStyle(fontSize: 30)),
              Text("Du pain", style: TextStyle(fontSize: 30)),
              Text("Du chocolat", style: TextStyle(fontSize: 30)),
              Text("Du curry", style: TextStyle(fontSize: 30)),
              Text("De la Pauline", style: TextStyle(fontSize: 30)),
              Text("Des Malterser", style: TextStyle(fontSize: 30)),
              Text("Du pain", style: TextStyle(fontSize: 30)),
              Text("Du chocolat", style: TextStyle(fontSize: 30)),
              Text("Du curry", style: TextStyle(fontSize: 30)),
              Text("De la Pauline", style: TextStyle(fontSize: 30)),
              Text("Des Malterser", style: TextStyle(fontSize: 30)),
              Text("Du pain", style: TextStyle(fontSize: 30)),
              Text("Du chocolat", style: TextStyle(fontSize: 30)),
              Text("Du curry", style: TextStyle(fontSize: 30)),
              Text("De la Pauline", style: TextStyle(fontSize: 30)),
              Text("Des Malterser", style: TextStyle(fontSize: 30)),
              Text("Du pain", style: TextStyle(fontSize: 30)),
              Text("Du chocolat", style: TextStyle(fontSize: 30)),
              Text("Du curry", style: TextStyle(fontSize: 30)),
              Text("De la Pauline", style: TextStyle(fontSize: 30)),
              Text("Des Malterser", style: TextStyle(fontSize: 30)),
              Text("Du pain", style: TextStyle(fontSize: 30)),
              Text("Du chocolat", style: TextStyle(fontSize: 30)),
              Text("Du curry", style: TextStyle(fontSize: 30)),
              Text("De la Pauline", style: TextStyle(fontSize: 30)),
              Text("Des Malterser", style: TextStyle(fontSize: 30)),
              Text("Du pain", style: TextStyle(fontSize: 30)),
              Text("Du chocolat", style: TextStyle(fontSize: 30)),
              Text("Du curry", style: TextStyle(fontSize: 30)),
              Text("De la Pauline", style: TextStyle(fontSize: 30)),
              Text("Des Malterser", style: TextStyle(fontSize: 30)),
              Text("Du pain", style: TextStyle(fontSize: 30)),
              Text("Du chocolat", style: TextStyle(fontSize: 30)),
              Text("Du curry", style: TextStyle(fontSize: 30)),
              Text("De la Pauline", style: TextStyle(fontSize: 30)),
              Text("Des Malterser", style: TextStyle(fontSize: 30)),
              Text("Du pain", style: TextStyle(fontSize: 30)),
              Text("Du chocolat", style: TextStyle(fontSize: 30)),
              Text("Du curry", style: TextStyle(fontSize: 30)),
              Text("De la Pauline", style: TextStyle(fontSize: 30)),
              Text("Des Malterser", style: TextStyle(fontSize: 30)),
              Text("Du pain", style: TextStyle(fontSize: 30)),
              Text("Du chocolat", style: TextStyle(fontSize: 30)),
              Text("Du curry", style: TextStyle(fontSize: 30)),
              Text("De la Pauline", style: TextStyle(fontSize: 30)),
              Text("Des Malterser", style: TextStyle(fontSize: 30)),
              Text("Du pain", style: TextStyle(fontSize: 30)),
              Text("Du chocolat", style: TextStyle(fontSize: 30)),
              Text("Du curry", style: TextStyle(fontSize: 30)),
              Text("De la Pauline", style: TextStyle(fontSize: 30)),
              Text("Des Malterser", style: TextStyle(fontSize: 30)),
              Text("Du pain", style: TextStyle(fontSize: 30)),
              Text("Du chocolat", style: TextStyle(fontSize: 30)),
              Text("Du curry", style: TextStyle(fontSize: 30)),
              Text("De la Pauline", style: TextStyle(fontSize: 30)),
              Text("Des Malterser", style: TextStyle(fontSize: 30)),
              Text("Du pain", style: TextStyle(fontSize: 30)),
              Text("Du chocolat", style: TextStyle(fontSize: 30)),
              Text("Du curry", style: TextStyle(fontSize: 30)),
              Text("De la Pauline", style: TextStyle(fontSize: 30)),
              Text("Des Malterser", style: TextStyle(fontSize: 30)),
              Text("Du pain", style: TextStyle(fontSize: 30)),
              Text("Du chocolat", style: TextStyle(fontSize: 30)),
              Text("Du curry", style: TextStyle(fontSize: 30)),
              Text("De la Pauline", style: TextStyle(fontSize: 30)),
              Text("Des Malterser", style: TextStyle(fontSize: 30)),
              Text("Du pain", style: TextStyle(fontSize: 30)),
              Text("Du chocolat", style: TextStyle(fontSize: 30)),
              Text("Du curry", style: TextStyle(fontSize: 30)),
              Text("De la Pauline", style: TextStyle(fontSize: 30)),
              Text("Des Malterser", style: TextStyle(fontSize: 30)),
              Text("Du pain", style: TextStyle(fontSize: 30)),
              Text("Du chocolat", style: TextStyle(fontSize: 30)),
              Text("Du curry", style: TextStyle(fontSize: 30)),
              Text("De la Pauline", style: TextStyle(fontSize: 30)),
              Text("Des Malterser", style: TextStyle(fontSize: 30)),
              Text("Du pain", style: TextStyle(fontSize: 30)),
              Text("Du chocolat", style: TextStyle(fontSize: 30)),
              Text("Du curry", style: TextStyle(fontSize: 30)),
              Text("De la Pauline", style: TextStyle(fontSize: 30)),
              Text("Des Malterser", style: TextStyle(fontSize: 30)),
              Text("Du pain", style: TextStyle(fontSize: 30)),
              Text("Du chocolat", style: TextStyle(fontSize: 30)),
              Text("Du curry", style: TextStyle(fontSize: 30)),
              Text("De la Pauline", style: TextStyle(fontSize: 30)),
              Text("Des Malterser", style: TextStyle(fontSize: 30)),
              Text("Du pain", style: TextStyle(fontSize: 30)),
              Text("Du chocolat", style: TextStyle(fontSize: 30)),
              Text("Du curry", style: TextStyle(fontSize: 30)),
              Text("De la Pauline", style: TextStyle(fontSize: 30)),
              Text("Des Malterser", style: TextStyle(fontSize: 30)),
              Text("Du pain", style: TextStyle(fontSize: 30)),
              Text("Du chocolat", style: TextStyle(fontSize: 30)),
              Text("Du curry", style: TextStyle(fontSize: 30)),
              Text("De la Pauline", style: TextStyle(fontSize: 30)),
              Text("Des Malterser", style: TextStyle(fontSize: 30)),
              Text("Du pain", style: TextStyle(fontSize: 30)),
              Text("Du chocolat", style: TextStyle(fontSize: 30)),
              Text("Du curry", style: TextStyle(fontSize: 30)),
              Text("De la Pauline", style: TextStyle(fontSize: 30)),
              Text("Des Malterser", style: TextStyle(fontSize: 30)),
            ],
          ),
        ),
      ),
    );
  }
}
