name: Flutter-CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  flutter_test:
    name: Run flutter test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.9'
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
      
      
  flutter_build_apk:
    name: Build for android APK
    runs-on: ubuntu-latest
    needs: flutter_test
    
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.9'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk
      - uses: actions/upload-artifact@v3
        with:
          name: my-app-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
          
  flutter_build_appbundle:
    name: Build for android AppBundle
    runs-on: ubuntu-latest
    needs: flutter_test
    
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.9'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build appbundle
      - uses: actions/upload-artifact@v3
        with:
          name: my-app-appbundle
          path: build/app/outputs/bundle/release/app-release.aab
          retention-days: 7
          
          
          
  flutter_build_ios:
    name: Build for IOS App
    runs-on: macos-latest
    needs: flutter_test
    
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.9'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - uses: actions/upload-artifact@v3
        with:
          name: my-app-ios-app
          path: /Users/runner/work/flutter-test-1/flutter-test-1/build/ios/iphoneos/Runner.app
          retention-days: 7
      
      
      
