name: Flutter-CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  flutter_test:
    name: Run flutter test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.9'
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
      
      
  flutter_build_android:
    name: Build for android
    runs-on: ubuntu-latest
    needs: flutter_test
    
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.9'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk
      
      
      
